function I(o,c){const d=document.createElement("a"),s=URL.createObjectURL(o);d.href=s,d.download=c,d.click(),setTimeout(()=>URL.revokeObjectURL(s),3e4)}async function L(o){if(!o.image)return null;const c=new Image;return c.src=o.image.src,await c.decode(),c}function O(o,c,d,s,m,p,l){const[f,g,r,i]=d.image.crop||[0,0,c.width,c.height],t=d.image.display==="product",h=t?Math.min(p/r,l/i):Math.max(p/r,l/i),a=r*h,n=i*h;o.save(),o.beginPath(),o.rect(s,m,p,l),o.clip(),t&&(o.fillStyle="#f3f3f1",o.fillRect(s,m,p,l)),o.drawImage(c,f,g,r,i,s+(p-a)/2,m+(l-n)/2,a,n),o.restore()}function R(o,c,d,s,m,p,l=4){let f="",g=0;const r=c.split(/\s+/);for(let i=0;i<r.length;i++){const t=f+(f?" ":"")+r[i];if(o.measureText(t).width>m&&f){if(o.fillText(f,d,s),s+=p,g++,f=r[i],g===l-1){let h=[f,...r.slice(i+1)].join(" ");for(;o.measureText(h+"\u2026").width>m&&h.length;)h=h.slice(0,-1);o.fillText(h+"\u2026",d,s);return}}else f=t}f&&o.fillText(f,d,s)}export async function exportImage(o,c,d){await document.fonts.ready;const s=o.filter(n=>/CC BY/.test(n.imageNote||"")),m=Math.max(2,Math.min(6,Math.ceil(Math.sqrt(o.length)))),p=1440,l=p/m,f=l+100,g=165,r=s.length?165:100,i=document.createElement("canvas");i.width=p,i.height=g+Math.ceil(o.length/m)*f+r;const t=i.getContext("2d");t.fillStyle="#000",t.fillRect(0,0,i.width,i.height),t.fillStyle="#fff",t.font="700 27px Poppins",t.fillText("prototipo ago",35,49),t.font="38px Roboto",t.fillText("Paleta de materiales",35,104),t.font="18px Roboto",t.fillStyle="#aaa",t.fillText(c.trim()||"Opciones para mi proyecto",35,140);const h=await Promise.all(o.map(L));o.forEach((n,x)=>{const u=x%m*l,e=g+Math.floor(x/m)*f,S=h[x];t.fillStyle="#30251b",t.fillRect(u,e,l,l),S?O(t,S,n,u,e,l,l):(t.font="28px Roboto",t.fillStyle="#eee",R(t,n.name,u+22,e+l/2,l-44,34),t.font="14px Roboto",t.fillText("Gu\xEDa de acabado \xB7 sin fotograf\xEDa",u+22,e+l-30)),t.fillStyle="#fff",t.font="18px Roboto",R(t,x+1+". "+n.name,u+15,e+l+27,l-30,22,2),t.fillStyle="#aaa",t.font="12px Roboto",R(t,[n.brand,n.code,n.finish].filter(Boolean).join(" \xB7 "),u+15,e+l+69,l-30,16,2)}),s.length&&(t.fillStyle="#aaa",t.font="13px Roboto",R(t,s.map(n=>n.name+": "+n.imageNote).join(" "),35,i.height-125,p-70,18,2),t.fillText("Licencia de la muestra de Puy: creativecommons.org/licenses/by-sa/3.0/",35,i.height-82)),t.fillStyle="#aaa",t.font="17px Roboto",t.fillText("prototipoago.com/materiales/ \xB7 El tono y las existencias se confirman con una muestra.",35,i.height-55),t.font="13px Roboto",t.fillText("Compartir la selecci\xF3n completa: usa \xABCopiar enlace\xBB en tu paleta.",35,i.height-27);const a=await new Promise(n=>i.toBlob(n,"image/png"));if(!a)throw Error("No pudimos crear la imagen. Prueba con una paleta m\xE1s peque\xF1a.");I(a,"AGO - Paleta de materiales.png")}export async function exportPDF(o,c,d){await document.fonts.ready;const s=new TextEncoder,m=[],p=[0];let l=0;const f=a=>{const n=typeof a=="string"?s.encode(a):a;m.push(n),l+=n.length},g=(a,n)=>{p[a]=l,f(a+` 0 obj
`);for(const x of n)f(x);f(`
endobj
`)},r=Math.ceil(o.length/6),i=Array.from({length:r},(a,n)=>5+n*4);f(`%PDF-1.4
`),g(1,["<< /Type /Catalog /Pages 2 0 R >>"]),g(2,["<< /Type /Pages /Count "+r+" /Kids ["+i.map(a=>a+" 0 R").join(" ")+"] >>"]);for(let a=0;a<r;a++){const n=o.slice(a*6,a*6+6),x=await Promise.all(n.map(L)),u=document.createElement("canvas");u.width=1200,u.height=1698;const e=u.getContext("2d");e.fillStyle="#000",e.fillRect(0,0,1200,1698),e.fillStyle="#fff",e.font="700 30px Poppins",e.fillText("prototipo ago",42,61),e.font="44px Roboto",e.fillText("Paleta de materiales",42,126),e.fillStyle="#aaa",e.font="21px Roboto",e.fillText(c.trim()||"Opciones para mi proyecto",42,165),n.forEach((b,j)=>{const T=42+j%2*573,w=204+Math.floor(j/2)*438,P=543,C=340,v=x[j];e.fillStyle="#30251b",e.fillRect(T,w,P,C),v?O(e,v,b,T,w,P,C):(e.fillStyle="#fff",e.font="32px Roboto",R(e,b.name,T+25,w+140,P-50,39,3),e.font="17px Roboto",e.fillText("Gu\xEDa de acabado \xB7 sin fotograf\xEDa",T+25,w+C-35)),e.fillStyle="#fff",e.font="26px Roboto",R(e,a*6+j+1+". "+b.name,T,w+C+34,P,31,1),e.fillStyle="#aaa",e.font="17px Roboto",R(e,[b.brand,b.code,b.finish].filter(Boolean).join(" \xB7 "),T,w+C+62,P,23,2)}),e.strokeStyle="#555",e.beginPath(),e.moveTo(42,1545),e.lineTo(1158,1545),e.stroke(),e.font="17px Roboto",e.fillStyle="#aaa",e.fillText("El tono y las existencias se confirman con una muestra.",42,1580);const S=n.filter(b=>/CC BY/.test(b.imageNote||""));S.length?(e.font="13px Roboto",e.fillText(S.map(b=>b.name+": "+b.imageNote).join(" "),42,1605),e.font="12px Roboto",e.fillText("Licencia de Puy: creativecommons.org/licenses/by-sa/3.0/ \xB7 Fuente completa en la ficha.",42,1622)):e.fillText("Cr\xE9ditos y referencias de las muestras en cada ficha del cat\xE1logo.",42,1608),e.font="17px Roboto",e.fillStyle="#fff",e.fillText("Abrir esta paleta en prototipoago.com/materiales/",42,1641),e.fillStyle="#aaa",e.fillText(a+1+" / "+r,1090,1641);const B=await new Promise(b=>u.toBlob(b,"image/jpeg",.92));if(!B)throw Error("No pudimos crear una p\xE1gina del PDF.");const E=new Uint8Array(await B.arrayBuffer()),y=3+a*4;g(y,["<< /Type /XObject /Subtype /Image /Width 1200 /Height 1698 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length "+E.length+` >>
stream
`,E,`
endstream`]);const M=`q
595.28 0 0 841.89 0 0 cm
/Im0 Do
Q
`;g(y+1,["<< /Length "+s.encode(M).length+` >>
stream
`+M+"endstream"]),g(y+2,["<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /Im0 "+y+" 0 R >> >> /Contents "+(y+1)+" 0 R /Annots ["+(y+3)+" 0 R] >>"]);const A=d.replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)");g(y+3,["<< /Type /Annot /Subtype /Link /Rect [18 20 540 46] /Border [0 0 0] /A << /S /URI /URI ("+A+") >> >>"])}const t=l,h=p.length;f(`xref
0 `+h+`
0000000000 65535 f 
`);for(let a=1;a<h;a++)f(String(p[a]).padStart(10,"0")+` 00000 n 
`);f(`trailer
<< /Size `+h+` /Root 1 0 R >>
startxref
`+t+`
%%EOF
`),I(new Blob(m,{type:"application/pdf"}),"AGO - Paleta de materiales.pdf")}
