function L(i,m){const g=document.createElement("a"),f=URL.createObjectURL(i);g.href=f,g.download=m,g.click(),setTimeout(()=>URL.revokeObjectURL(f),3e4)}async function O(i){if(!i.image)return null;const m=new Image;return m.src=i.image.src,await m.decode(),m}function B(i,m,g,f,d,u,a=4){let n="",c=0;const x=m.split(/\s+/);for(let r=0;r<x.length;r++){const t=n+(n?" ":"")+x[r];if(i.measureText(t).width>d&&n){if(i.fillText(n,g,f),f+=u,c++,n=x[r],c===a-1){let h=[n,...x.slice(r+1)].join(" ");for(;i.measureText(h+"\u2026").width>d&&h.length;)h=h.slice(0,-1);i.fillText(h+"\u2026",g,f);return}}else n=t}n&&i.fillText(n,g,f)}export async function exportImage(i,m,g){await document.fonts.ready;const f=i.filter(l=>/CC BY/.test(l.imageNote||"")),d=Math.max(2,Math.min(6,Math.ceil(Math.sqrt(i.length)))),u=1440,a=u/d,n=a+100,c=165,x=f.length?165:100,r=document.createElement("canvas");r.width=u,r.height=c+Math.ceil(i.length/d)*n+x;const t=r.getContext("2d");t.fillStyle="#000",t.fillRect(0,0,r.width,r.height),t.fillStyle="#fff",t.font="700 27px Poppins",t.fillText("prototipo ago",35,49),t.font="38px Roboto",t.fillText("Paleta de materiales",35,104),t.font="18px Roboto",t.fillStyle="#aaa",t.fillText(m.trim()||"Opciones para mi proyecto",35,140);const h=await Promise.all(i.map(O));i.forEach((l,R)=>{const s=R%d*a,e=c+Math.floor(R/d)*n,b=h[R];if(t.fillStyle="#30251b",t.fillRect(s,e,a,a),b){const E=Math.max(a/b.width,a/b.height),j=b.width*E,y=b.height*E;t.save(),t.beginPath(),t.rect(s,e,a,a),t.clip(),t.drawImage(b,s+(a-j)/2,e+(a-y)/2,j,y),t.restore()}else t.font="28px Roboto",t.fillStyle="#eee",B(t,l.name,s+22,e+a/2,a-44,34),t.font="14px Roboto",t.fillText("Gu\xEDa de acabado \xB7 sin fotograf\xEDa",s+22,e+a-30);t.fillStyle="#fff",t.font="18px Roboto",B(t,R+1+". "+l.name,s+15,e+a+27,a-30,22,2),t.fillStyle="#aaa",t.font="12px Roboto",B(t,[l.brand,l.code,l.finish].filter(Boolean).join(" \xB7 "),s+15,e+a+69,a-30,16,2)}),f.length&&(t.fillStyle="#aaa",t.font="13px Roboto",B(t,f.map(l=>l.name+": "+l.imageNote).join(" "),35,r.height-125,u-70,18,2),t.fillText("Licencia de la muestra de Puy: creativecommons.org/licenses/by-sa/3.0/",35,r.height-82)),t.fillStyle="#aaa",t.font="17px Roboto",t.fillText("prototipoago.com/materiales/ \xB7 El tono y las existencias se confirman con una muestra.",35,r.height-55),t.font="13px Roboto",t.fillText("Compartir la selecci\xF3n completa: usa \xABCopiar enlace\xBB en tu paleta.",35,r.height-27);const o=await new Promise(l=>r.toBlob(l,"image/png"));if(!o)throw Error("No pudimos crear la imagen. Prueba con una paleta m\xE1s peque\xF1a.");L(o,"AGO - Paleta de materiales.png")}export async function exportPDF(i,m,g){await document.fonts.ready;const f=new TextEncoder,d=[],u=[0];let a=0;const n=o=>{const l=typeof o=="string"?f.encode(o):o;d.push(l),a+=l.length},c=(o,l)=>{u[o]=a,n(o+` 0 obj
`);for(const R of l)n(R);n(`
endobj
`)},x=Math.ceil(i.length/6),r=Array.from({length:x},(o,l)=>5+l*4);n(`%PDF-1.4
`),c(1,["<< /Type /Catalog /Pages 2 0 R >>"]),c(2,["<< /Type /Pages /Count "+x+" /Kids ["+r.map(o=>o+" 0 R").join(" ")+"] >>"]);for(let o=0;o<x;o++){const l=i.slice(o*6,o*6+6),R=await Promise.all(l.map(O)),s=document.createElement("canvas");s.width=1200,s.height=1698;const e=s.getContext("2d");e.fillStyle="#000",e.fillRect(0,0,1200,1698),e.fillStyle="#fff",e.font="700 30px Poppins",e.fillText("prototipo ago",42,61),e.font="44px Roboto",e.fillText("Paleta de materiales",42,126),e.fillStyle="#aaa",e.font="21px Roboto",e.fillText(m.trim()||"Opciones para mi proyecto",42,165),l.forEach((p,D)=>{const T=42+D%2*573,w=204+Math.floor(D/2)*438,S=543,P=340,C=R[D];if(e.fillStyle="#30251b",e.fillRect(T,w,S,P),C){const v=Math.max(S/C.width,P/C.height),A=C.width*v,I=C.height*v;e.save(),e.beginPath(),e.rect(T,w,S,P),e.clip(),e.drawImage(C,T+(S-A)/2,w+(P-I)/2,A,I),e.restore()}else e.fillStyle="#fff",e.font="32px Roboto",B(e,p.name,T+25,w+140,S-50,39,3),e.font="17px Roboto",e.fillText("Gu\xEDa de acabado \xB7 sin fotograf\xEDa",T+25,w+P-35);e.fillStyle="#fff",e.font="26px Roboto",B(e,o*6+D+1+". "+p.name,T,w+P+34,S,31,1),e.fillStyle="#aaa",e.font="17px Roboto",B(e,[p.brand,p.code,p.finish].filter(Boolean).join(" \xB7 "),T,w+P+62,S,23,2)}),e.strokeStyle="#555",e.beginPath(),e.moveTo(42,1545),e.lineTo(1158,1545),e.stroke(),e.font="17px Roboto",e.fillStyle="#aaa",e.fillText("El tono y las existencias se confirman con una muestra.",42,1580);const b=l.filter(p=>/CC BY/.test(p.imageNote||""));b.length?(e.font="13px Roboto",e.fillText(b.map(p=>p.name+": "+p.imageNote).join(" "),42,1605),e.font="12px Roboto",e.fillText("Licencia de Puy: creativecommons.org/licenses/by-sa/3.0/ \xB7 Fuente completa en la ficha.",42,1622)):e.fillText("Cr\xE9ditos y referencias de las muestras en cada ficha del cat\xE1logo.",42,1608),e.font="17px Roboto",e.fillStyle="#fff",e.fillText("Abrir esta paleta en prototipoago.com/materiales/",42,1641),e.fillStyle="#aaa",e.fillText(o+1+" / "+x,1090,1641);const E=await new Promise(p=>s.toBlob(p,"image/jpeg",.92));if(!E)throw Error("No pudimos crear una p\xE1gina del PDF.");const j=new Uint8Array(await E.arrayBuffer()),y=3+o*4;c(y,["<< /Type /XObject /Subtype /Image /Width 1200 /Height 1698 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length "+j.length+` >>
stream
`,j,`
endstream`]);const M=`q
595.28 0 0 841.89 0 0 cm
/Im0 Do
Q
`;c(y+1,["<< /Length "+f.encode(M).length+` >>
stream
`+M+"endstream"]),c(y+2,["<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /Im0 "+y+" 0 R >> >> /Contents "+(y+1)+" 0 R /Annots ["+(y+3)+" 0 R] >>"]);const F=g.replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)");c(y+3,["<< /Type /Annot /Subtype /Link /Rect [18 20 540 46] /Border [0 0 0] /A << /S /URI /URI ("+F+") >> >>"])}const t=a,h=u.length;n(`xref
0 `+h+`
0000000000 65535 f 
`);for(let o=1;o<h;o++)n(String(u[o]).padStart(10,"0")+` 00000 n 
`);n(`trailer
<< /Size `+h+` /Root 1 0 R >>
startxref
`+t+`
%%EOF
`),L(new Blob(d,{type:"application/pdf"}),"AGO - Paleta de materiales.pdf")}
